# The Fujifilm camera
# These parameters are used to feed the film simulation
camera:
  model: X-T4
  serialNb: 593536303034201113C58330314721
  firmware: 1.00

# Fujifilm X-Raw Studio
xrfc:
  version: 1.12.0.0
  # path of the folder into which the FP1 film simulations will be generated
  fp1Path: FP1
